### ISSUE TITLE
The pump component panics abnormally

### ISSUE THREAD

**Issue by Buddy-Yuan** [pingcap/tidb-binlog#1225]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Starting the pump component reports an error

2. What did you expect to see?
The pump component does not panic

3. What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2b0 pc=0x1cb8c7c]

goroutine 193051696 [running]:
google.golang.org/grpc.(*ClientConn).GetState(...)
        /root/go/pkg/mod/google.golang.org/grpc@v1.44.0/clientconn.go:527
github.com/tikv/client-go/v2/internal/client.(*RPCClient).SendRequest(0x4001502d00, {0x3b2a6a8, 0x40006242c0}, {0x40028260a8, 0x12}, 0x4004307180, 0x6fc23ac00?)
        /root/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220311043619-5042c6f2aaa6/internal/client/client.go:410 +0x54c
github.com/tikv/client-go/v2/internal/client.interceptedClient.SendRequest({{0x3b1af50?, 0x4001502d00?}}, {0x3b2a6a8, 0x40006242c0}, {0x40028260a8, 0x12}, 0x1001?, 0x6fc23ac00)
        /root/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220311043619-5042c6f2aaa6/internal/client/client_interceptor.go:42 +0x160
github.com/tikv/client-go/v2/internal/client.reqCollapse.SendRequest({{0x3b1ce68?, 0x40018081a0?}}, {0x3b2a6a8, 0x40006242c0}, {0x40028260a8, 0x12}, 0x4005322601?, 0x2?)
        /root/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220311043619-5042c6f2aaa6/internal/client/client_collapse.go:74 +0x9c
github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS.func1({0x3b2a6a8, 0x40006242c0}, 0x0?, 0x4f, {0x40028260a8, 0x12})
        /root/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220311043619-5042c6f2aaa6/tikv/kv.go:540 +0x14c
created by github.com/tikv/client-go/v2/tikv.(*KVStore).updateSafeTS
        /root/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.1-0.20220311043619-5042c6f2aaa6/tikv/kv.go:538 +0x7
```

4. Please provide the relate downstream type and version of drainer.
(run `drainer -V` in terminal to get drainer's version)

```
pump -V
Release Version: v6.1.1
Git Commit Hash: 2e8bd50ccfcdfa2261d5a6649b7f4ef16b73c7f3
Build TS: 2022-08-23 08:26:06
Go Version: go1.18.5
Go OS/Arch: linux/arm64
```

**Comment by D3Hunter** [comment]
duplicate with https://github.com/pingcap/tidb-binlog/issues/1170
